### ISSUE TITLE
SPI: Overly supportive

### ISSUE THREAD

**Issue by robert-hh1** [WinnerMicro/micropython#11]
In my test SPI ID 0 worked instantly. That's good. I noticed however, that there is a behavior which intended to be supportive but may also be a burden. In the definition of the  interface you have to specify as CS pin. In the API, the default is set to PB_15. When sending & receiving, this pin is pulled low by the driver. That is convenient, when there is only a single slave on the bus. However, SPI uses a shared bus. When having more than one device, one cannot use that automatic feature. Instead, as usually separate pins have to be used as CS, eventually combined with an external AND gate,  while the "automatic" pin cannot be used for something else. Since the SPI driver of the SDK uses DMA, aligning the timing will be a little bit tricky.
Using the SW SPI device, this cs parameter must not be used, and CS can be assigned freely.

**Comment by wdyichen** [comment]
W600's CS can be freely controlled by software using ordinary IO, so we can consider improving it.

**Comment by robert-hh** [comment]
For that purpose I looked into the WM_SDK. It seemed to me, that CS has to be specified and will be used. If this cannot be changed, SPI can also be repeatedly be initialized, if other CS pins have to be used. Instead of calling:
`dev1_cs.value(0)` or `dev2_cs.value(0)` for the different devices, 
one can also 
`call spi.init( ...., dev1_cs)` or `spi.init(...., dev2_cs)`. 
That is a little bit more bytecode and a little bit slower.
